### ISSUE TITLE
Error when progressing to Select Data Provider

### ISSUE THREAD

**Issue by danielcrenna** [jlattimer/D365CustomDataProvider#1]
Using your example I was able to get to the point where I can choose the Chuck Norris Joke Data Provider from the list on "Select Data Provider", but can't save that data source after giving it a name due to what looks like a false negative with that entity's ID.

The Fault Exception has this message: `Microsoft.Xrm.Sdk.Data.Exceptions.InvalidMetadataException: ExternalName is null or empty for attribute 'lat_chucknorrisdatasourceid' of entity lat_chucknorrisdatasource`

Which prevents saving the data source and moving on.

I'm using Dynamics 365 online (trial) against the latest NuGet registration tool when setting up these entities.

I created a new publisher with "lat" prefix just to be pedantic/cohesive to the example since I'm in new territory.

**Comment by danielcrenna** [comment]
I was able to add my own ExternalName because somehow the data source entity made it in after the Plugin Registration Tool crashed. I don't know why ExternalName is omitted by that tool during creation and why it would create an entity non-transactionally.

**Comment by jlattimer** [comment]
:) yeah - I noticed the crashes as well. Glad you got it figured out!

**Comment by danielcrenna** [comment]
Still doesn’t seem to be a way to profile/debug the native virtual entity fetch but one horrible workaround I’m thinking about is making a custom PostOperation step that just clears the collection and repeats the fetch; not for production obviously but it just might work.

**Comment by jlattimer** [comment]
Indeed, that would certainly be helpful

**Comment by ryanmichaeljames** [comment]
Thanks @danielcrenna for your fix. I struggled with this for a while.

I'd like to clarify what @danielcrenna meant by adding his own `ExternalName`. If you open the field mentioned in the error, in this case `lat_chucknorrisdatasourceid`, you'll notice the field named 'ExternalName' is empty.

**Comment by fahadmajeedrana** [comment]
Thank you for the details. Are you able to use the custom provider in UUI? In UUI subgrid doesn't load the data at all. I am also receiving errors getting the records through webapi through rest.

**Comment by jlattimer** [comment]
No idea there
